[package]
name = "hinton"
version = "0.1.0"
authors = ["Fausto German <fgermanj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Run `cargo run --features bench_time | show_bytecode`
show_bytecode = []
show_raw_bytecode = []

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
hashbrown = "0.11"