edition = "2021"

max_width = 120
use_field_init_shorthand = true
tab_spaces = 2
chain_width = 100
enum_discrim_align_threshold = 20
fn_single_line = true
format_macro_matchers = true
format_macro_bodies = true
overflow_delimited_expr = true
single_line_if_else_max_width = 75
struct_lit_width = 30
